### ISSUE TITLE
Events with message longer than 8k are not logged

### ISSUE THREAD

**Issue by barbushin** [graze/dog-statsd#14]
There is a problem with logging messages that are longer than 8k, DataDog agent is failed with error: 
```
Traceback (most recent call last):
  File "dogstatsd.pyc", line 420, in start
  File "aggregator.pyc", line 612, in submit_packets
  File "aggregator.pyc", line 467, in parse_metric_packet
Exception: Unparseable metric packet:
```

Maybe this messages should be split in multiple packets to be sent by fwrite() or there must be some message size limit that will be stripped before sending to DataDog agent.

**Comment by h-bragg** [comment]
Interesting.

1. Do you have the message that was sent that made it fall over?
1. Was it a lot of metrics in a single call `->increment(['thing','second',..],1);` or just a really big message `->event('bla bla bla');` ?

The bit of code in the datadog agent where it is falling over is parsing a standard metric rather than an event or service check. But write may chunk the messages it self and it is attempting to parse a partial message, hence failing.

**Comment by barbushin** [comment]
It was just a big message `->event('bla bla')`. I've tested is with `->event(str_repeat('x', 10000))` - also fails.

**Comment by h-bragg** [comment]
Looks like this is relevant:

http://php.net/manual/en/function.fwrite.php
> **Note:**
> Writing to a network stream may end before the whole string is written. Return value of fwrite() may be checked:
> ```php
> function fwrite_stream($fp, $string) {
>     for ($written = 0; $written < strlen($string); $written += $fwrite) {
>         $fwrite = fwrite($fp, substr($string, $written));
>         if ($fwrite === false) {
>             return $written;
>         }
>     }
>     return $written;
> }
> ?>
> ```

**Comment by h-bragg** [comment]
Will merge the writing refactor in tomorrow and add a PR with this change too.

**Comment by h-bragg** [comment]
@barbushin I have updated master, and tested with a local echo udp server... Does this change help?
